language: rust
env:
  global:
    - secure: HGiC3rE+ciEr2V14atcLXZfOqQ6fStDNYN4vo9rNqqBUPhcmjC8EuQHJoaei13IHbRNgEEuw3Ajc3dRIXwY/t7gBxLIMIZ7iannrc8Pscf6wcqOi2eSjJLMVRWzh3D/ZF+Bq680NrfpdO8U7wVQK+NkwQGIGrx0tD9NhHLoHDBk=
script:
  - cd rustecs
  - cargo test --verbose
  - cargo doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
